# Schema for the configuration files of the Bluesky Post module.
bsky_post.settings:
  type: config_object
  label: 'Bluesky Post settings'
  mapping:
    example:
      type: string
      label: 'Example'
